# Generated by Django 3.2.5 on 2021-12-06 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.TextField(default=None, max_length=20)),
                ('company_name', models.TextField(max_length=20)),
                ('location', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('enquiry_no', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
