# Generated by Django 3.0.5 on 2022-01-20 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.TextField(default=None, max_length=20)),
                ('company_name', models.TextField(max_length=20)),
                ('location', models.TextField()),
                ('email_id', models.EmailField(max_length=254)),
                ('enquiry_no', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message=' 10 digits allowed.', regex='^[6-9]\\d{9}$')])),
                ('list', models.IntegerField(default=None)),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
