# Generated by Django 3.2.5 on 2021-12-21 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='list',
            field=models.IntegerField(default=None),
        ),
    ]
