# Generated by Django 3.2.5 on 2021-12-26 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_company_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='enquiry_no',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message=' 10 digits allowed.', regex='^[6-9]\\d{9}$')]),
        ),
    ]
