# Generated by Django 3.2.5 on 2021-12-06 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0003_alter_service_table'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SSN', models.CharField(max_length=20, unique=True)),
                ('email_id', models.EmailField(max_length=254)),
                ('contact_no', models.CharField(max_length=10)),
                ('asset_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
                ('room_no', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='location.location')),
            ],
            options={
                'db_table': 'usermodel',
            },
        ),
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_ssn', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='usermodel.usermodel')),
                ('asset_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='asset.asset')),
            ],
            options={
                'db_table': 'accessed_by',
            },
        ),
    ]
