# Generated by Django 3.2.5 on 2021-12-09 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0002_usermodel_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='asset_id',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='room_no',
        ),
        migrations.DeleteModel(
            name='Access',
        ),
    ]
