# Generated by Django 3.0.5 on 2022-01-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('barcode_id', models.CharField(default=None, max_length=20, unique=True)),
            ],
            options={
                'db_table': 'barcode',
            },
        ),
        migrations.CreateModel(
            name='SAP_Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('capitalized_date', models.DateField()),
                ('cost_center', models.CharField(max_length=20)),
                ('asset_description', models.TextField()),
            ],
            options={
                'db_table': 'SAP_asset',
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('barcode_id', models.CharField(default=None, max_length=20, unique=True)),
                ('cost_center', models.CharField(max_length=20)),
                ('asset_description', models.TextField()),
                ('capitalized_date', models.DateField()),
                ('found_status', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='company.Company')),
                ('room_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='location.Location')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
