# Generated by Django 3.2.5 on 2021-12-06 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('barcode_id', models.CharField(max_length=20, unique=True)),
                ('cost_center', models.CharField(max_length=20)),
                ('asset_description', models.TextField()),
                ('capitalized_date', models.DateField()),
                ('found_status', models.BooleanField(default=False)),
                ('company_id', models.ForeignKey(max_length=20, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'db_table': 'asset',
            },
        ),
    ]
