# Generated by Django 3.2.5 on 2021-12-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_auto_20211210_0034'),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='room_no',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='location.location'),
        ),
    ]
