# Generated by Django 3.2.5 on 2021-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_room_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='SAP_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=20, unique=True)),
                ('capitalized_date', models.DateField()),
                ('cost_center', models.CharField(max_length=20)),
                ('asset_description', models.TextField()),
            ],
            options={
                'db_table': 'SAP_asset',
            },
        ),
    ]
