# Generated by Django 3.2.5 on 2021-12-11 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_asset_room_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='capitalized_date',
            field=models.DateField(default=None),
        ),
    ]
