# Generated by Django 3.0.5 on 2022-01-20 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermodel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('room_no', models.CharField(max_length=20, unique=True)),
                ('list_assets', models.IntegerField(max_length=20)),
                ('incharge', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usermodel.UserModel')),
            ],
            options={
                'db_table': 'location',
            },
        ),
    ]
