# Generated by Django 3.2.5 on 2021-12-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_service'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='service',
            table='service',
        ),
    ]
