# Generated by Django 3.2.5 on 2021-12-09 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermodel', '0003_auto_20211210_0034'),
        ('location', '0003_alter_service_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='incharge',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='usermodel.usermodel'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
